use_frameworks!

platform :ios, '12.0'

target 'XPBase_Example' do
  pod 'XPBase', :path => '../'
  pod 'Moya'
  pod 'HandyJSON'
  #nav管理
  pod 'GKNavigationBar/NavigationBar', '1.9.7'

  target 'XPBase_Tests' do
    inherit! :search_paths

    # pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
