use_frameworks!

platform :ios, '11.0'

target 'XPBase_Example' do
  pod 'XPBase', :path => '../'
  pod 'Moya'
  pod 'HandyJSON'

  target 'XPBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
